### ISSUE TITLE
Bug IDK 1.20.6

### ISSUE THREAD

**Issue by makumaku1974** [ChongYuCN/Craft-Time#1]
For some reason. Ive been stuck with this mod for minutes and could not figure how to craft the flint crafting table. I used REI and still no recipe... Please fix this ASAP.

**Comment by ChongYu668** [comment]
This is my negligence. The recipe content for 1.20.6 has been changed from "item" to "id", so it does not take effect. I will update when the official version 1.21 is released.

**Comment by makumaku1974** [comment]
okay thanks.
